In [1]:
import pandas as pd

In [12]:
# Series
values = [10, 20, 30, 40, 50]
s = pd.Series(values, index=['a', 'b', 'c', 'd', 'e'])

s

a    10
b    20
c    30
d    40
a    50
dtype: int64

In [11]:
s.loc['a']
# using index I can quickly access to individual rows

a    10
a    50
dtype: int64

In [41]:
# Dataframe

df = pd.DataFrame({
    'name': ['Anna', 'Béla', 'Cecil', 'Dávid', 'Elemér'],
    'age': [10, 20, 30, 40, 50]
})

df

     name  age
0    Anna   10
1    Béla   20
2   Cecil   30
3   Dávid   40
4  Elemér   50

In [21]:
df = df.set_index('name')
df.loc['Anna']

age    10
Name: Anna, dtype: int64

In [32]:
df1 = pd.DataFrame({
    'a': [1, 2, 3]
}, index=[0, 1, 2])

df2 = pd.DataFrame({
    'a': [10, 20, 30]
}, index=[1, 2, 0])

In [33]:
df1 + df2

    a
0  31
1  12
2  23

In [40]:
df = df.reset_index()

   index    name  age
0      0    Anna   10
1      1    Béla   20
2      2   Cecil   30
3      3   Dávid   40
4      4  Elemér   50

In [42]:
df

     name  age
0    Anna   10
1    Béla   20
2   Cecil   30
3   Dávid   40
4  Elemér   50

In [43]:
df.to_dict()

{'name': {0: 'Anna', 1: 'Béla', 2: 'Cecil', 3: 'Dávid', 4: 'Elemér'},
 'age': {0: 10, 1: 20, 2: 30, 3: 40, 4: 50}}

In [44]:
df.to_json()

'{"name":{"0":"Anna","1":"B\\u00e9la","2":"Cecil","3":"D\\u00e1vid","4":"Elem\\u00e9r"},"age":{"0":10,"1":20,"2":30,"3":40,"4":50}}'

In [58]:
df.to_csv('mydata.csv', index=False)

In [46]:
df.to_html()

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>name</th>\n      <th>age</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Anna</td>\n      <td>10</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Béla</td>\n      <td>20</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Cecil</td>\n      <td>30</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Dávid</td>\n      <td>40</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Elemér</td>\n      <td>50</td>\n    </tr>\n  </tbody>\n</table>'

In [47]:
df.to_numpy()

array([['Anna', 10],
       ['Béla', 20],
       ['Cecil', 30],
       ['Dávid', 40],
       ['Elemér', 50]], dtype=object)

In [56]:
aaa = pd.read_csv('mydata.csv', index_col=0)

In [57]:
aaa

     name  age
0    Anna   10
1    Béla   20
2   Cecil   30
3   Dávid   40
4  Elemér   50