In [1]:
import pandas as pd

In [43]:
df = pd.DataFrame({
    'name': ['Anna', 'Béla', 'Cecil', 'Dávid', 'Elemér'],
    'age': [25, 35, 30, 40, 50],
    'job': ['Developer', 'HR', 'Manager', 'Business Analyst', 'Tester']
})

df

     name  age               job
0    Anna   25         Developer
1    Béla   35                HR
2   Cecil   30           Manager
3   Dávid   40  Business Analyst
4  Elemér   50            Tester

In [3]:
df.loc[1]

name    Béla
age       35
job       HR
Name: 1, dtype: object

In [4]:
df = df.set_index('name')
df

        age               job
name
Anna     25         Developer
Béla     35                HR
Cecil    30           Manager
Dávid    40  Business Analyst
Elemér   50            Tester

In [5]:
df.loc['Anna']

age           25
job    Developer
Name: Anna, dtype: object

In [6]:
df.iloc[0]

age           25
job    Developer
Name: Anna, dtype: object

In [7]:
int(df.loc['Anna', 'age'])

25

In [8]:
df.at['Anna', 'age']

np.int64(25)

In [9]:
df.at['Anna', 'age'] = 60

In [10]:
df

        age               job
name
Anna     60         Developer
Béla     35                HR
Cecil    30           Manager
Dávid    40  Business Analyst
Elemér   50            Tester

In [49]:
df.loc['Pierluigi'] = [80, 'retired']

ValueError: cannot set a row with mismatched columns

In [12]:
df.iloc[4:6]

           age      job
name
Elemér      50   Tester
Pierluigi   80  retired

In [13]:
df.iloc[-1, 1]
# row and column ranges

'retired'

In [16]:
def myfunction(x: str):
    if x.endswith('r'):
        return x + ' !!'
    else:
        return x + ' $'

In [25]:
df.job = df.job.apply(myfunction)

In [50]:
df

     name   age               job
0    Anna   NaN         Developer
1    Béla  35.0                HR
2   Cecil  30.0           Manager
3   Dávid  40.0  Business Analyst
4  Elemér  50.0            Tester

In [28]:
df['summary'] = df.apply(lambda row: f'Age: {row.age}, job: {row.job}', axis=1)

In [31]:
df.drop('summary', axis = 1, inplace = True)

In [72]:
df

                name   age               job
0               Anna   NaN         Developer
1               Béla  35.0                HR
2              Cecil  30.0           Manager
3              Dávid  40.0  Business Analyst
4             Elemér  50.0            Tester
Pierluigi  Pierluigi   NaN           retired

In [45]:
df.at[0, 'age'] = float('nan')

In [55]:
df.info()

<class 'pandas.DataFrame'>
Index: 6 entries, 0 to Pierluigi
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      str
 1   age     4 non-null      float64
 2   job     6 non-null      str
dtypes: float64(1), str(2)
memory usage: 364.0+ bytes

In [48]:
df.dropna()

     name   age               job
1    Béla  35.0                HR
2   Cecil  30.0           Manager
3   Dávid  40.0  Business Analyst
4  Elemér  50.0            Tester

In [54]:
df.loc['Pierluigi'] = ['Pierluigi', float('nan'), 'retired']

In [58]:
df.fillna(-1)

                name   age               job
0               Anna  -1.0         Developer
1               Béla  35.0                HR
2              Cecil  30.0           Manager
3              Dávid  40.0  Business Analyst
4             Elemér  50.0            Tester
Pierluigi  Pierluigi  -1.0           retired

In [59]:
df.notna()

           name    age   job
0          True  False  True
1          True   True  True
2          True   True  True
3          True   True  True
4          True   True  True
Pierluigi  True  False  True

In [62]:
df[df.age >= 40]

     name   age               job
3   Dávid  40.0  Business Analyst
4  Elemér  50.0            Tester

In [65]:
df[[True, False, True, False, True, False]]

     name   age        job
0    Anna   NaN  Developer
2   Cecil  30.0    Manager
4  Elemér  50.0     Tester

In [70]:
(df.age > 44) & (df.job.notna())

0            False
1            False
2            False
3            False
4             True
Pierluigi    False
dtype: bool