In [1]:
from sklearn.datasets import fetch_california_housing

In [2]:
data = fetch_california_housing(as_frame=True).frame

In [3]:
data

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [4]:
data.shape

(20640, 9)

In [6]:
data['HouseAge']

0        41.0
1        21.0
2        52.0
3        52.0
4        52.0
         ...
20635    25.0
20636    18.0
20637    17.0
20638    18.0
20639    16.0
Name: HouseAge, Length: 20640, dtype: float64

In [7]:
data[data['HouseAge'] < 5]

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
59,2.5625,2.0,2.771930,0.754386,94.0,1.649123,37.82,-122.29,0.60000
854,2.8750,2.0,5.624161,1.979866,240.0,1.610738,37.59,-122.01,2.37500
871,6.0824,3.0,5.090447,1.039230,7205.0,2.617145,37.52,-122.07,2.73500
882,4.1387,4.0,4.470167,1.184964,1606.0,1.916468,37.55,-121.96,1.62500
946,5.1437,4.0,4.964807,1.046481,2937.0,1.950199,37.72,-121.92,2.99400
...,...,...,...,...,...,...,...,...,...
20103,3.5714,4.0,5.964029,1.082734,676.0,2.431655,37.98,-120.35,1.49500
20367,8.0428,3.0,8.239437,1.042254,493.0,3.471831,34.16,-118.94,5.00001
20424,6.6122,4.0,7.568645,1.225193,6187.0,2.803353,34.18,-118.75,3.57600
20427,8.6499,4.0,7.236059,1.032528,5495.0,2.553439,34.19,-118.80,5.00001
20437,5.7160,4.0,5.506924,1.099940,3950.0,2.378085,34.25,-118.81,3.20800

In [8]:
data[['HouseAge', 'AveRooms']]

       HouseAge  AveRooms
0          41.0  6.984127
1          21.0  6.238137
2          52.0  8.288136
3          52.0  5.817352
4          52.0  6.281853
...         ...       ...
20635      25.0  5.045455
20636      18.0  6.114035
20637      17.0  5.205543
20638      18.0  5.329513
20639      16.0  5.254717

[20640 rows x 2 columns]