In [2]:
import pandas as pd
import numpy as np

data = {
'School ID': [101, 102, 103, np.nan, 105, 106, 107, 108],
'Name': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
'Address': ['123 Main St', '456 Oak Ave', '789 Pine Ln', '101 Elm St', np.nan, '222 Maple Rd', '444 Cedar Blvd', '555 Birch Dr'],
'City': ['Mumbai', 'Delhi', 'Bengaluru', 'Chennai', 'Kolkata', np.nan, 'Pune', 'Jaipur'],
'Subject': ['Math', 'English', 'Science', 'Math', 'History', 'Math', 'Science', 'English'],
'Marks': [85, 92, 78, 89, np.nan, 95, 80, 88],
'Rank': [2, 1, 4, 3, 8, 1, 5, 3],
'Grade': ['B', 'A', 'C', 'B', 'D', 'A', 'C', 'B']
}

df = pd.DataFrame(data)

df

   School ID Name         Address       City  Subject  Marks  Rank Grade
0      101.0    A     123 Main St     Mumbai     Math   85.0     2     B
1      102.0    B     456 Oak Ave      Delhi  English   92.0     1     A
2      103.0    C     789 Pine Ln  Bengaluru  Science   78.0     4     C
3        NaN    D      101 Elm St    Chennai     Math   89.0     3     B
4      105.0    E             NaN    Kolkata  History    NaN     8     D
5      106.0    F    222 Maple Rd        NaN     Math   95.0     1     A
6      107.0    G  444 Cedar Blvd       Pune  Science   80.0     5     C
7      108.0    H    555 Birch Dr     Jaipur  English   88.0     3     B

# Removing Rows with Missing Values

In [3]:
df_cleaned = df.dropna()

df_cleaned

   School ID Name         Address       City  Subject  Marks  Rank Grade
0      101.0    A     123 Main St     Mumbai     Math   85.0     2     B
1      102.0    B     456 Oak Ave      Delhi  English   92.0     1     A
2      103.0    C     789 Pine Ln  Bengaluru  Science   78.0     4     C
6      107.0    G  444 Cedar Blvd       Pune  Science   80.0     5     C
7      108.0    H    555 Birch Dr     Jaipur  English   88.0     3     B

# Imputation Methods

replacing missing values with the mean, median or mode of the relevant variable

- Pros: easy, fast, suitable for numeric variables
- Cons: may distort the true distribution of the data

In [4]:
mean_imputation = df['Marks'].fillna(df['Marks'].mean())
median_imputation = df['Marks'].fillna(df['Marks'].median())
mode_imputation = df['Marks'].fillna(df['Marks'].mode().iloc[0])
# .iloc[0]: Accesses the first element of the Series which represents the mode.

print("\nImputation using Mean:")
print(mean_imputation)

print("\nImputation using Median:")
print(median_imputation)

print("\nImputation using Mode:")
print(mode_imputation)

Imputation using Mean:
0    85.000000
1    92.000000
2    78.000000
3    89.000000
4    86.714286
5    95.000000
6    80.000000
7    88.000000
Name: Marks, dtype: float64

Imputation using Median:
0    85.0
1    92.0
2    78.0
3    89.0
4    88.0
5    95.0
6    80.0
7    88.0
Name: Marks, dtype: float64

Imputation using Mode:
0    85.0
1    92.0
2    78.0
3    89.0
4    78.0
5    95.0
6    80.0
7    88.0
Name: Marks, dtype: float64

# Forward and Backward Fill

These methods fill missing values using the closest available values in the column. They are useful for ordered or time-series data.

In [8]:
forward_fill = df['Marks'].ffill()
backward_fill = df['Marks'].bfill()

print("\nForward Fill:")
print(forward_fill)

print("\nBackward Fill:")
print(backward_fill)

Forward Fill:
0    85.0
1    92.0
2    78.0
3    89.0
4    89.0
5    95.0
6    80.0
7    88.0
Name: Marks, dtype: float64

Backward Fill:
0    85.0
1    92.0
2    78.0
3    89.0
4    95.0
5    95.0
6    80.0
7    88.0
Name: Marks, dtype: float64

# Interpolation Techniques

Interpolation estimates missing values by using the trend or pattern of surrounding data points.

In [9]:
linear_interpolation = df['Marks'].interpolate(method='linear')
quadratic_interpolation = df['Marks'].interpolate(method='quadratic')

print("\nLinear Interpolation:")
print(linear_interpolation)

print("\nQuadratic Interpolation:")
print(quadratic_interpolation)

Linear Interpolation:
0    85.0
1    92.0
2    78.0
3    89.0
4    92.0
5    95.0
6    80.0
7    88.0
Name: Marks, dtype: float64

Quadratic Interpolation:
0    85.00000
1    92.00000
2    78.00000
3    89.00000
4    98.28024
5    95.00000
6    80.00000
7    88.00000
Name: Marks, dtype: float64