# Challenge - Simple mean prediction

In [41]:
import pandas as pd

df = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [53]:
from sklearn.model_selection import train_test_split

# Split data

features = ["PassengerId", "Pclass", "Sex", "Age", "SibSp", "Parch", "Embarked"]
target = "Survived"
X = df[features]
y = df[target]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1
)

In [54]:
from sklearn.impute import SimpleImputer

# Handle missing values

most_frequent_imputer = SimpleImputer(strategy="most_frequent")
X_train[["Embarked"]] = most_frequent_imputer.fit_transform(X_train[["Embarked"]])
X_test[["Embarked"]] = most_frequent_imputer.transform(X_test[["Embarked"]])

mean_imputer = SimpleImputer(strategy="mean")
X_train[["Age"]] = mean_imputer.fit_transform(X_train[["Age"]])
X_test[["Age"]] = mean_imputer.transform(X_test[["Age"]])

X_train[:5]

     PassengerId  Pclass     Sex        Age  SibSp  Parch Embarked
301          302       3    male  30.166232      2      0        Q
309          310       1  female  30.000000      0      0        C
516          517       2  female  34.000000      0      0        S
120          121       2    male  21.000000      2      0        S
570          571       2    male  62.000000      0      0        S

In [55]:
print(X_train.isnull().sum(), "\n")
print(X_test.isnull().sum())

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Embarked       0
dtype: int64

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Embarked       0
dtype: int64

In [39]:


# Handling categorical data


# OH_encoder = OneHotEncoder(drop="first", handle_unknown='ignore', sparse_output=False)
# object_cols = ["Sex", "Embarked"]
#
# OH_cols_train = pd.DataFrame(OH_encoder.fit_transform(X_train[object_cols]))
# OH_cols_test = pd.DataFrame(OH_encoder.transform(X_test[object_cols]))
#
# One-hot encoding removed index; put it back
# OH_cols_train.index = X_train.index
# OH_cols_test.index = X_test.index
#
# Remove categorical columns (will replace with one-hot encoding)
# num_X_train = X_train.drop(object_cols, axis=1)
# num_X_valid = X_test.drop(object_cols, axis=1)
#
# Add one-hot encoded columns to numerical features
# OH_X_train = pd.concat([num_X_train, OH_cols_train], axis=1)
# OH_X_test = pd.concat([num_X_valid, OH_cols_test], axis=1)
#
# OH_X_train[:5]

     Pclass     Sex        Age  SibSp  Parch    0    1
301       3    male  30.166232      2      0  1.0  0.0
309       1  female  30.000000      0      0  0.0  0.0
516       2  female  34.000000      0      0  0.0  1.0
120       2    male  21.000000      2      0  0.0  1.0
570       2    male  62.000000      0      0  0.0  1.0

In [56]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [57]:
from sklearn.preprocessing import OrdinalEncoder

# Handling categorical data - ordinal encoder is enough, we would do the same with one hot encoder too
ordinal_encoder = OrdinalEncoder()
object_cols = ["Sex", "Embarked"]

X_train[object_cols] = ordinal_encoder.fit_transform(X_train[object_cols])
X_test[object_cols] = ordinal_encoder.transform(X_test[object_cols])

In [58]:
X_train

     PassengerId  Pclass  Sex        Age  SibSp  Parch  Embarked
301          302       3  1.0  30.166232      2      0       1.0
309          310       1  0.0  30.000000      0      0       0.0
516          517       2  0.0  34.000000      0      0       2.0
120          121       2  1.0  21.000000      2      0       2.0
570          571       2  1.0  62.000000      0      0       2.0
..           ...     ...  ...        ...    ...    ...       ...
715          716       3  1.0  19.000000      0      0       2.0
767          768       3  0.0  30.500000      0      0       1.0
72            73       2  1.0  21.000000      0      0       2.0
235          236       3  0.0  30.166232      0      0       2.0
37            38       3  1.0  21.000000      0      0       2.0

[712 rows x 7 columns]

In [59]:
print(X_train.isnull().sum(), "\n")
print(X_test.isnull().sum())

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Embarked       0
dtype: int64

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Embarked       0
dtype: int64

In [60]:
# preparing data for model

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=1)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=1)

In [61]:
preds = model.predict(X_test)

In [63]:
submission = pd.DataFrame({
    "PassengerId": X_test["PassengerId"],
    "Survived": preds
})

submission[:5]

     PassengerId  Survived
862          863         1
223          224         0
84            85         1
680          681         1
535          536         1